### ISSUE TITLE
Rsync should follow symlinks

### ISSUE THREAD

**Issue by jshrake** [Oblong/obi#37]

**Comment by jshrake** [comment]
According to http://docs.fabfile.org/en/1.10/api/contrib/project.html, we can use `extra_opts` to pass `-K` or `-L` to `rsync_project`. See https://github.com/Oblong/obi/blob/master/obi/task/task.py#L238-L242

**Comment by davidnixon** [comment]
@jshrake I do not have permission to push a branch here but here is a patch file.

[0001-add-support-for-rsync-extra-opts-in-project.yaml.patch.gz](https://github.com/Oblong/obi/files/321066/0001-add-support-for-rsync-extra-opts-in-project.yaml.patch.gz)
```diff
         local_dir=env.local_project_dir,
         remote_dir=parent_dir(env.project_dir),
         delete=True,
+        extra_opts=env.config.get("rsync-extra-opts", ""),
         exclude=env.config.get("rsync-excludes", []))
 
 def parent_dir(current_dir):
```

```yaml
# Rsync task
# -----------
# Comma-separated list of files to ignore when rsyncing to remote machines
rsync-excludes: [".git", "build", "CMakeFiles"]
rsync-extra-opts: "--stats -k"
```
